name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ] # Make sure this matches your primary branch name

permissions: # <--- THIS BLOCK IS IMPORTANT
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... rest of your steps ...
      - name: Commit and Push to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot
          branch: gh-pages # This is where the action pushes